/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  525
#define VERSION_USER   "lundman"
#define VERSION_HOST   "shinken.interq.or.jp"
#define VERSION_DATE   "Sat May  5 10:27:14 2012"
#define VERSION_STRING "lundman@shinken.interq.or.jp build 525 (Sat May  5 10:27:14 2012)"

/* Lundtastic services */
